language: python
python:
  - "3.4"
  - "3.4-dev" # 3.4 development branch
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "nightly"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  [
    "python -m unittest UnitTesting/test_proj_man.py",
    "python -m unittest UnitTesting/test_proj_stats.py",
    "python -m unittest UnitTesting/test_task.py",
    "python -m unittest UnitTesting/test_task_happy.py",
    "python -m unittest UnitTesting/test_parser.py"
  ]
